---
env:
  browser: true
  es6: true
  node: true
  mocha: true

extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:node/recommended

parserOptions:
  ecmaVersion: 2018
  sourceType: module

rules:
  indent: ["error", 4]
  linebreak-style: ["error", "unix"]
  quotes: ["error", "double"]
  semi: ["error", "always"]
  no-console: off
  import/extensions: off